###
POST http://localhost:5000/api/v1/people/person HTTP/1.1
Content-Type: application/json

{
  "name":"Yaneth",
  "lastname":"Mejía",
  "dni":"1053888",
  "address":[{
    "city":"Manizales",
    "code_zip":170002,
    "geo":[-6.125152,8.23923]
  }]
}
###
GET http://localhost:5000/api/v1/people HTTP/1.1
###
GET http://localhost:5000/api/v1/people/ HTTP/1.1
###
PUT http://localhost:5000/api/v1/people/ HTTP/1.1
Content-Type: application/json

{
  "address":[{
    "city":"Manizales",
    "code_zip":170005,
    "geo":[-6.125152,8.23923]
  }]
}
###
DELETE http://localhost:5000/api/v1/people/ HTTP/1.1
###
POST http://localhost:5000/api/v1/superheroes_v2/superhero HTTP/1.1
Content-Type: application/json

{
  "superhero":"Batman",
  "realname": "Bruce Wayne",
  "superpower": "Be rich"
}
###
GET http://localhost:5000/api/v1/superheroes_v2 HTTP/1.1
###
GET http://localhost:5000/api/v1/superheroes_v2/623b1e92591a935032b04cbd HTTP/1.1

###
PUT http://localhost:5000/api/v1/superheroes_v2/623b1e92591a935032b04cbd HTTP/1.1
Content-Type: application/json

{
  "superpower": "Be SOOOO rich"
}
###
DELETE http://localhost:5000/api/v1/superheroes_v2/623b1e92591a935032b04cbd HTTP/1.1
